---
  Kubernetes.create_rollout_and_delete_deployment:
  -
    args:
      image: busybox
      replicas: 3
      command:
      - sleep
      - "3600"
      env:
      - name: "UPD"
        value: "false"
      changes:
        env:
        - name: "UPD"
          value: "true"
    runner:
      type: constant
      concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 1
        retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
  -
    args:
      image: busybox
      replicas: 3
      command:
      - sleep
      - "3600"
      env:
      - name: "UPD"
        value: "false"
      changes:
        env:
        - name: "UPD"
          value: "true"
    runner:
      type: rps
      rps: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 1
        retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
